<?php

use Illuminate\Database\Seeder;

class NationalityTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

        DB::table("nationality")->insert([ "code" => "US", "name" => "United States", "displayname" => "United States", "description" => "United States", "numsort" => 10, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AF", "name" => "Afghanistan", "displayname" => "Afghanistan", "description" => "Afghanistan", "numsort" => 20, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AL", "name" => "Albania", "displayname" => "Albania", "description" => "Albania", "numsort" => 30, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DZ", "name" => "Algeria", "displayname" => "Algeria", "description" => "Algeria", "numsort" => 40, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AS", "name" => "American Samoa", "displayname" => "American Samoa", "description" => "American Samoa", "numsort" => 50, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AD", "name" => "Andorra", "displayname" => "Andorra", "description" => "Andorra", "numsort" => 60, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AO", "name" => "Angola", "displayname" => "Angola", "description" => "Angola", "numsort" => 70, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AI", "name" => "Anguilla", "displayname" => "Anguilla", "description" => "Anguilla", "numsort" => 80, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AQ", "name" => "Antarctica", "displayname" => "Antarctica", "description" => "Antarctica", "numsort" => 90, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AG", "name" => "Antigua and Barbuda", "displayname" => "Antigua and Barbuda", "description" => "Antigua and Barbuda", "numsort" => 100, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AR", "name" => "Argentina", "displayname" => "Argentina", "description" => "Argentina", "numsort" => 110, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AM", "name" => "Armenia", "displayname" => "Armenia", "description" => "Armenia", "numsort" => 120, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AW", "name" => "Aruba", "displayname" => "Aruba", "description" => "Aruba", "numsort" => 130, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AU", "name" => "Australia", "displayname" => "Australia", "description" => "Australia", "numsort" => 140, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AT", "name" => "Austria", "displayname" => "Austria", "description" => "Austria", "numsort" => 150, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AZ", "name" => "Azerbaijan", "displayname" => "Azerbaijan", "description" => "Azerbaijan", "numsort" => 160, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BS", "name" => "Bahamas", "displayname" => "Bahamas", "description" => "Bahamas", "numsort" => 170, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BH", "name" => "Bahrain", "displayname" => "Bahrain", "description" => "Bahrain", "numsort" => 180, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BD", "name" => "Bangladesh", "displayname" => "Bangladesh", "description" => "Bangladesh", "numsort" => 190, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BB", "name" => "Barbados", "displayname" => "Barbados", "description" => "Barbados", "numsort" => 200, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BY", "name" => "Belarus", "displayname" => "Belarus", "description" => "Belarus", "numsort" => 210, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BE", "name" => "Belgium", "displayname" => "Belgium", "description" => "Belgium", "numsort" => 220, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BZ", "name" => "Belize", "displayname" => "Belize", "description" => "Belize", "numsort" => 230, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BJ", "name" => "Benin", "displayname" => "Benin", "description" => "Benin", "numsort" => 240, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BM", "name" => "Bermuda", "displayname" => "Bermuda", "description" => "Bermuda", "numsort" => 250, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BT", "name" => "Bhutan", "displayname" => "Bhutan", "description" => "Bhutan", "numsort" => 260, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BO", "name" => "Bolivia", "displayname" => "Bolivia", "description" => "Bolivia", "numsort" => 270, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BA", "name" => "Bosnia-Herzegovina", "displayname" => "Bosnia-Herzegovina", "description" => "Bosnia-Herzegovina", "numsort" => 280, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BW", "name" => "Botswana", "displayname" => "Botswana", "description" => "Botswana", "numsort" => 290, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BV", "name" => "Bouvet Island", "displayname" => "Bouvet Island", "description" => "Bouvet Island", "numsort" => 300, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BR", "name" => "Brazil", "displayname" => "Brazil", "description" => "Brazil", "numsort" => 310, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IO", "name" => "British Indian Ocean Territory", "displayname" => "British Indian Ocean Territory", "description" => "British Indian Ocean Territory", "numsort" => 320, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BN", "name" => "Brunei Darussalam", "displayname" => "Brunei Darussalam", "description" => "Brunei Darussalam", "numsort" => 330, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BG", "name" => "Bulgaria", "displayname" => "Bulgaria", "description" => "Bulgaria", "numsort" => 340, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BF", "name" => "Burkina Faso", "displayname" => "Burkina Faso", "description" => "Burkina Faso", "numsort" => 350, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "BI", "name" => "Burundi", "displayname" => "Burundi", "description" => "Burundi", "numsort" => 360, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KH", "name" => "Cambodia", "displayname" => "Cambodia", "description" => "Cambodia", "numsort" => 370, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CM", "name" => "Cameroon", "displayname" => "Cameroon", "description" => "Cameroon", "numsort" => 380, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CV", "name" => "Cape Verde", "displayname" => "Cape Verde", "description" => "Cape Verde", "numsort" => 390, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KY", "name" => "Cayman Islands", "displayname" => "Cayman Islands", "description" => "Cayman Islands", "numsort" => 400, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CF", "name" => "Central African Republic", "displayname" => "Central African Republic", "description" => "Central African Republic", "numsort" => 410, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TD", "name" => "Chad", "displayname" => "Chad", "description" => "Chad", "numsort" => 420, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CL", "name" => "Chile", "displayname" => "Chile", "description" => "Chile", "numsort" => 430, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CN", "name" => "China", "displayname" => "China", "description" => "China", "numsort" => 440, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CX", "name" => "Christmas Island", "displayname" => "Christmas Island", "description" => "Christmas Island", "numsort" => 450, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CC", "name" => "Cocos (Keeling) Islands", "displayname" => "Cocos (Keeling) Islands", "description" => "Cocos (Keeling) Islands", "numsort" => 460, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CO", "name" => "Colombia", "displayname" => "Colombia", "description" => "Colombia", "numsort" => 470, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KM", "name" => "Comoros", "displayname" => "Comoros", "description" => "Comoros", "numsort" => 480, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CG", "name" => "Congo", "displayname" => "Congo", "description" => "Congo", "numsort" => 490, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CD", "name" => "Congo (Democratic Republic)", "displayname" => "Congo (Democratic Republic)", "description" => "Congo (Democratic Republic)", "numsort" => 500, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CK", "name" => "Cook Islands", "displayname" => "Cook Islands", "description" => "Cook Islands", "numsort" => 510, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CR", "name" => "Costa Rica", "displayname" => "Costa Rica", "description" => "Costa Rica", "numsort" => 520, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HR", "name" => "Croatia", "displayname" => "Croatia", "description" => "Croatia", "numsort" => 530, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CU", "name" => "Cuba", "displayname" => "Cuba", "description" => "Cuba", "numsort" => 540, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CY", "name" => "Cyprus", "displayname" => "Cyprus", "description" => "Cyprus", "numsort" => 550, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CZ", "name" => "Czech Republic", "displayname" => "Czech Republic", "description" => "Czech Republic", "numsort" => 560, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DK", "name" => "Denmark", "displayname" => "Denmark", "description" => "Denmark", "numsort" => 570, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DJ", "name" => "Djibouti", "displayname" => "Djibouti", "description" => "Djibouti", "numsort" => 580, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DM", "name" => "Dominica", "displayname" => "Dominica", "description" => "Dominica", "numsort" => 590, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DO", "name" => "Dominican Republic", "displayname" => "Dominican Republic", "description" => "Dominican Republic", "numsort" => 600, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TP", "name" => "East Timor", "displayname" => "East Timor", "description" => "East Timor", "numsort" => 610, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "EC", "name" => "Ecuador", "displayname" => "Ecuador", "description" => "Ecuador", "numsort" => 620, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "EG", "name" => "Egypt", "displayname" => "Egypt", "description" => "Egypt", "numsort" => 630, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SV", "name" => "El Salvador", "displayname" => "El Salvador", "description" => "El Salvador", "numsort" => 640, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GQ", "name" => "Equatorial Guinea", "displayname" => "Equatorial Guinea", "description" => "Equatorial Guinea", "numsort" => 650, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ER", "name" => "Eritrea", "displayname" => "Eritrea", "description" => "Eritrea", "numsort" => 660, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "EE", "name" => "Estonia", "displayname" => "Estonia", "description" => "Estonia", "numsort" => 670, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ET", "name" => "Ethiopia", "displayname" => "Ethiopia", "description" => "Ethiopia", "numsort" => 680, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FK", "name" => "Falkland Islands", "displayname" => "Falkland Islands", "description" => "Falkland Islands", "numsort" => 690, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FO", "name" => "Faroe Islands", "displayname" => "Faroe Islands", "description" => "Faroe Islands", "numsort" => 700, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FJ", "name" => "Fiji", "displayname" => "Fiji", "description" => "Fiji", "numsort" => 710, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FI", "name" => "Finland", "displayname" => "Finland", "description" => "Finland", "numsort" => 720, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FR", "name" => "France", "displayname" => "France", "description" => "France", "numsort" => 730, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FX", "name" => "France (European Territory)", "displayname" => "France (European Territory)", "description" => "France (European Territory)", "numsort" => 740, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GF", "name" => "French Guiana", "displayname" => "French Guiana", "description" => "French Guiana", "numsort" => 750, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TF", "name" => "French Southern Territories", "displayname" => "French Southern Territories", "description" => "French Southern Territories", "numsort" => 760, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GA", "name" => "Gabon", "displayname" => "Gabon", "description" => "Gabon", "numsort" => 770, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GM", "name" => "Gambia", "displayname" => "Gambia", "description" => "Gambia", "numsort" => 780, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GE", "name" => "Georgia", "displayname" => "Georgia", "description" => "Georgia", "numsort" => 790, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "DE", "name" => "Germany", "displayname" => "Germany", "description" => "Germany", "numsort" => 800, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GH", "name" => "Ghana", "displayname" => "Ghana", "description" => "Ghana", "numsort" => 810, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GI", "name" => "Gibraltar", "displayname" => "Gibraltar", "description" => "Gibraltar", "numsort" => 820, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GR", "name" => "Greece", "displayname" => "Greece", "description" => "Greece", "numsort" => 830, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GL", "name" => "Greenland", "displayname" => "Greenland", "description" => "Greenland", "numsort" => 840, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GD", "name" => "Grenada", "displayname" => "Grenada", "description" => "Grenada", "numsort" => 850, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GP", "name" => "Guadeloupe", "displayname" => "Guadeloupe", "description" => "Guadeloupe", "numsort" => 860, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GU", "name" => "Guam", "displayname" => "Guam", "description" => "Guam", "numsort" => 870, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GT", "name" => "Guatemala", "displayname" => "Guatemala", "description" => "Guatemala", "numsort" => 880, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GN", "name" => "Guinea", "displayname" => "Guinea", "description" => "Guinea", "numsort" => 890, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GW", "name" => "Guinea Bissau", "displayname" => "Guinea Bissau", "description" => "Guinea Bissau", "numsort" => 900, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GY", "name" => "Guyana", "displayname" => "Guyana", "description" => "Guyana", "numsort" => 910, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HT", "name" => "Haiti", "displayname" => "Haiti", "description" => "Haiti", "numsort" => 920, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HM", "name" => "Heard and McDonald Islands", "displayname" => "Heard and McDonald Islands", "description" => "Heard and McDonald Islands", "numsort" => 930, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "VA", "name" => "Holy See (Vatican)", "displayname" => "Holy See (Vatican)", "description" => "Holy See (Vatican)", "numsort" => 940, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HN", "name" => "Honduras", "displayname" => "Honduras", "description" => "Honduras", "numsort" => 950, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HK", "name" => "Hong Kong", "displayname" => "Hong Kong", "description" => "Hong Kong", "numsort" => 960, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "HU", "name" => "Hungary", "displayname" => "Hungary", "description" => "Hungary", "numsort" => 970, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IS", "name" => "Iceland", "displayname" => "Iceland", "description" => "Iceland", "numsort" => 980, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IN", "name" => "India", "displayname" => "India", "description" => "India", "numsort" => 990, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ID", "name" => "Indonesia", "displayname" => "Indonesia", "description" => "Indonesia", "numsort" => 1000, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IR", "name" => "Iran", "displayname" => "Iran", "description" => "Iran", "numsort" => 1010, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IQ", "name" => "Iraq", "displayname" => "Iraq", "description" => "Iraq", "numsort" => 1020, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IE", "name" => "Ireland", "displayname" => "Ireland", "description" => "Ireland", "numsort" => 1030, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IL", "name" => "Israel", "displayname" => "Israel", "description" => "Israel", "numsort" => 1040, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "IT", "name" => "Italy", "displayname" => "Italy", "description" => "Italy", "numsort" => 1050, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CI", "name" => "Ivory Coast (Cote D'Ivoire)", "displayname" => "Ivory Coast (Cote D'Ivoire)", "description" => "Ivory Coast (Cote D'Ivoire)", "numsort" => 1060, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "JM", "name" => "Jamaica", "displayname" => "Jamaica", "description" => "Jamaica", "numsort" => 1070, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "JP", "name" => "Japan", "displayname" => "Japan", "description" => "Japan", "numsort" => 1080, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "JO", "name" => "Jordan", "displayname" => "Jordan", "description" => "Jordan", "numsort" => 1090, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KZ", "name" => "Kazakhstan", "displayname" => "Kazakhstan", "description" => "Kazakhstan", "numsort" => 1100, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KE", "name" => "Kenya", "displayname" => "Kenya", "description" => "Kenya", "numsort" => 1110, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KI", "name" => "Kiribati", "displayname" => "Kiribati", "description" => "Kiribati", "numsort" => 1120, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KW", "name" => "Kuwait", "displayname" => "Kuwait", "description" => "Kuwait", "numsort" => 1130, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KG", "name" => "Kyrgyzstan", "displayname" => "Kyrgyzstan", "description" => "Kyrgyzstan", "numsort" => 1140, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LA", "name" => "Laos", "displayname" => "Laos", "description" => "Laos", "numsort" => 1150, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LV", "name" => "Latvia", "displayname" => "Latvia", "description" => "Latvia", "numsort" => 1160, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LB", "name" => "Lebanon", "displayname" => "Lebanon", "description" => "Lebanon", "numsort" => 1170, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LS", "name" => "Lesotho", "displayname" => "Lesotho", "description" => "Lesotho", "numsort" => 1180, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LR", "name" => "Liberia", "displayname" => "Liberia", "description" => "Liberia", "numsort" => 1190, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LY", "name" => "Libya", "displayname" => "Libya", "description" => "Libya", "numsort" => 1200, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LI", "name" => "Liechtenstein", "displayname" => "Liechtenstein", "description" => "Liechtenstein", "numsort" => 1210, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LT", "name" => "Lithuania", "displayname" => "Lithuania", "description" => "Lithuania", "numsort" => 1220, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LU", "name" => "Luxembourg", "displayname" => "Luxembourg", "description" => "Luxembourg", "numsort" => 1230, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MO", "name" => "Macau", "displayname" => "Macau", "description" => "Macau", "numsort" => 1240, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MK", "name" => "Macedonia", "displayname" => "Macedonia", "description" => "Macedonia", "numsort" => 1250, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MG", "name" => "Madagascar", "displayname" => "Madagascar", "description" => "Madagascar", "numsort" => 1260, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MW", "name" => "Malawi", "displayname" => "Malawi", "description" => "Malawi", "numsort" => 1270, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MY", "name" => "Malaysia", "displayname" => "Malaysia", "description" => "Malaysia", "numsort" => 1280, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MV", "name" => "Maldives", "displayname" => "Maldives", "description" => "Maldives", "numsort" => 1290, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ML", "name" => "Mali", "displayname" => "Mali", "description" => "Mali", "numsort" => 1300, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MT", "name" => "Malta", "displayname" => "Malta", "description" => "Malta", "numsort" => 1310, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MH", "name" => "Marshall Islands", "displayname" => "Marshall Islands", "description" => "Marshall Islands", "numsort" => 1320, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MQ", "name" => "Martinique", "displayname" => "Martinique", "description" => "Martinique", "numsort" => 1330, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MR", "name" => "Mauritania", "displayname" => "Mauritania", "description" => "Mauritania", "numsort" => 1340, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MU", "name" => "Mauritius", "displayname" => "Mauritius", "description" => "Mauritius", "numsort" => 1350, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "YT", "name" => "Mayotte", "displayname" => "Mayotte", "description" => "Mayotte", "numsort" => 1360, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MX", "name" => "Mexico", "displayname" => "Mexico", "description" => "Mexico", "numsort" => 1370, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "FM", "name" => "Micronesia", "displayname" => "Micronesia", "description" => "Micronesia", "numsort" => 1380, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MD", "name" => "Moldova", "displayname" => "Moldova", "description" => "Moldova", "numsort" => 1390, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MC", "name" => "Monaco", "displayname" => "Monaco", "description" => "Monaco", "numsort" => 1400, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MN", "name" => "Mongolia", "displayname" => "Mongolia", "description" => "Mongolia", "numsort" => 1410, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MS", "name" => "Montserrat", "displayname" => "Montserrat", "description" => "Montserrat", "numsort" => 1420, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MA", "name" => "Morocco", "displayname" => "Morocco", "description" => "Morocco", "numsort" => 1430, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MZ", "name" => "Mozambique", "displayname" => "Mozambique", "description" => "Mozambique", "numsort" => 1440, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MM", "name" => "Myanmar", "displayname" => "Myanmar", "description" => "Myanmar", "numsort" => 1450, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NA", "name" => "Namibia", "displayname" => "Namibia", "description" => "Namibia", "numsort" => 1460, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NR", "name" => "Nauru", "displayname" => "Nauru", "description" => "Nauru", "numsort" => 1470, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NP", "name" => "Nepal", "displayname" => "Nepal", "description" => "Nepal", "numsort" => 1480, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NL", "name" => "Netherlands", "displayname" => "Netherlands", "description" => "Netherlands", "numsort" => 1490, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "AN", "name" => "Netherlands Antilles", "displayname" => "Netherlands Antilles", "description" => "Netherlands Antilles", "numsort" => 1500, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NC", "name" => "New Caledonia", "displayname" => "New Caledonia", "description" => "New Caledonia", "numsort" => 1510, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NZ", "name" => "New Zealand", "displayname" => "New Zealand", "description" => "New Zealand", "numsort" => 1520, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NI", "name" => "Nicaragua", "displayname" => "Nicaragua", "description" => "Nicaragua", "numsort" => 1530, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NE", "name" => "Niger", "displayname" => "Niger", "description" => "Niger", "numsort" => 1540, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NG", "name" => "Nigeria", "displayname" => "Nigeria", "description" => "Nigeria", "numsort" => 1550, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NU", "name" => "Niue", "displayname" => "Niue", "description" => "Niue", "numsort" => 1560, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NF", "name" => "Norfolk Island", "displayname" => "Norfolk Island", "description" => "Norfolk Island", "numsort" => 1570, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KP", "name" => "North Korea", "displayname" => "North Korea", "description" => "North Korea", "numsort" => 1580, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "MP", "name" => "Northern Mariana Islands", "displayname" => "Northern Mariana Islands", "description" => "Northern Mariana Islands", "numsort" => 1590, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "NO", "name" => "Norway", "displayname" => "Norway", "description" => "Norway", "numsort" => 1600, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "OM", "name" => "Oman", "displayname" => "Oman", "description" => "Oman", "numsort" => 1610, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PK", "name" => "Pakistan", "displayname" => "Pakistan", "description" => "Pakistan", "numsort" => 1620, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PW", "name" => "Palau", "displayname" => "Palau", "description" => "Palau", "numsort" => 1630, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PS", "name" => "Palestinian Territory", "displayname" => "Palestinian Territory", "description" => "Palestinian Territory", "numsort" => 1640, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PA", "name" => "Panama", "displayname" => "Panama", "description" => "Panama", "numsort" => 1650, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PG", "name" => "Papua New Guinea", "displayname" => "Papua New Guinea", "description" => "Papua New Guinea", "numsort" => 1660, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PY", "name" => "Paraguay", "displayname" => "Paraguay", "description" => "Paraguay", "numsort" => 1670, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PE", "name" => "Peru", "displayname" => "Peru", "description" => "Peru", "numsort" => 1680, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PH", "name" => "Philippines", "displayname" => "Philippines", "description" => "Philippines", "numsort" => 1690, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PN", "name" => "Pitcairn", "displayname" => "Pitcairn", "description" => "Pitcairn", "numsort" => 1700, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PL", "name" => "Poland", "displayname" => "Poland", "description" => "Poland", "numsort" => 1710, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PF", "name" => "Polynesia", "displayname" => "Polynesia", "description" => "Polynesia", "numsort" => 1720, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PT", "name" => "Portugal", "displayname" => "Portugal", "description" => "Portugal", "numsort" => 1730, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PR", "name" => "Puerto Rico", "displayname" => "Puerto Rico", "description" => "Puerto Rico", "numsort" => 1740, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "QA", "name" => "Qatar", "displayname" => "Qatar", "description" => "Qatar", "numsort" => 1750, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "RE", "name" => "Reunion", "displayname" => "Reunion", "description" => "Reunion", "numsort" => 1760, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "RO", "name" => "Romania", "displayname" => "Romania", "description" => "Romania", "numsort" => 1770, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "RU", "name" => "Russian Federation", "displayname" => "Russian Federation", "description" => "Russian Federation", "numsort" => 1780, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "RW", "name" => "Rwanda", "displayname" => "Rwanda", "description" => "Rwanda", "numsort" => 1790, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "GS", "name" => "S. Georgia & S. Sandwich Isls.", "displayname" => "S. Georgia & S. Sandwich Isls.", "description" => "S. Georgia & S. Sandwich Isls.", "numsort" => 1800, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SH", "name" => "Saint Helena", "displayname" => "Saint Helena", "description" => "Saint Helena", "numsort" => 1810, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KN", "name" => "Saint Kitts & Nevis Anguilla", "displayname" => "Saint Kitts & Nevis Anguilla", "description" => "Saint Kitts & Nevis Anguilla", "numsort" => 1820, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LC", "name" => "Saint Lucia", "displayname" => "Saint Lucia", "description" => "Saint Lucia", "numsort" => 1830, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "PM", "name" => "Saint Pierre and Miquelon", "displayname" => "Saint Pierre and Miquelon", "description" => "Saint Pierre and Miquelon", "numsort" => 1840, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "VC", "name" => "Saint Vincent & Grenadines", "displayname" => "Saint Vincent & Grenadines", "description" => "Saint Vincent & Grenadines", "numsort" => 1850, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "WS", "name" => "Samoa", "displayname" => "Samoa", "description" => "Samoa", "numsort" => 1860, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SM", "name" => "San Marino", "displayname" => "San Marino", "description" => "San Marino", "numsort" => 1870, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ST", "name" => "Sao Tome and Principe", "displayname" => "Sao Tome and Principe", "description" => "Sao Tome and Principe", "numsort" => 1880, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SA", "name" => "Saudi Arabia", "displayname" => "Saudi Arabia", "description" => "Saudi Arabia", "numsort" => 1890, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SN", "name" => "Senegal", "displayname" => "Senegal", "description" => "Senegal", "numsort" => 1900, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SC", "name" => "Seychelles", "displayname" => "Seychelles", "description" => "Seychelles", "numsort" => 1910, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SL", "name" => "Sierra Leone", "displayname" => "Sierra Leone", "description" => "Sierra Leone", "numsort" => 1920, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SG", "name" => "Singapore", "displayname" => "Singapore", "description" => "Singapore", "numsort" => 1930, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SK", "name" => "Slovakia", "displayname" => "Slovakia", "description" => "Slovakia", "numsort" => 1940, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SI", "name" => "Slovenia", "displayname" => "Slovenia", "description" => "Slovenia", "numsort" => 1950, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SB", "name" => "Solomon Islands", "displayname" => "Solomon Islands", "description" => "Solomon Islands", "numsort" => 1960, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SO", "name" => "Somalia", "displayname" => "Somalia", "description" => "Somalia", "numsort" => 1970, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ZA", "name" => "South Africa", "displayname" => "South Africa", "description" => "South Africa", "numsort" => 1980, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "KR", "name" => "South Korea", "displayname" => "South Korea", "description" => "South Korea", "numsort" => 1990, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "ES", "name" => "Spain", "displayname" => "Spain", "description" => "Spain", "numsort" => 2000, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "LK", "name" => "Sri Lanka", "displayname" => "Sri Lanka", "description" => "Sri Lanka", "numsort" => 2010, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SD", "name" => "Sudan", "displayname" => "Sudan", "description" => "Sudan", "numsort" => 2020, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SR", "name" => "Suriname", "displayname" => "Suriname", "description" => "Suriname", "numsort" => 2030, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SZ", "name" => "Swaziland", "displayname" => "Swaziland", "description" => "Swaziland", "numsort" => 2040, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SE", "name" => "Sweden", "displayname" => "Sweden", "description" => "Sweden", "numsort" => 2050, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "CH", "name" => "Switzerland", "displayname" => "Switzerland", "description" => "Switzerland", "numsort" => 2060, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "SY", "name" => "Syrian Arab Republic", "displayname" => "Syrian Arab Republic", "description" => "Syrian Arab Republic", "numsort" => 2070, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TW", "name" => "Taiwan", "displayname" => "Taiwan", "description" => "Taiwan", "numsort" => 2080, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TJ", "name" => "Tajikistan", "displayname" => "Tajikistan", "description" => "Tajikistan", "numsort" => 2090, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TZ", "name" => "Tanzania", "displayname" => "Tanzania", "description" => "Tanzania", "numsort" => 2100, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TH", "name" => "Thailand", "displayname" => "Thailand", "description" => "Thailand", "numsort" => 2110, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TG", "name" => "Togo", "displayname" => "Togo", "description" => "Togo", "numsort" => 2120, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TK", "name" => "Tokelau", "displayname" => "Tokelau", "description" => "Tokelau", "numsort" => 2130, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TO", "name" => "Tonga", "displayname" => "Tonga", "description" => "Tonga", "numsort" => 2140, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TT", "name" => "Trinidad and Tobago", "displayname" => "Trinidad and Tobago", "description" => "Trinidad and Tobago", "numsort" => 2150, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TN", "name" => "Tunisia", "displayname" => "Tunisia", "description" => "Tunisia", "numsort" => 2160, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TR", "name" => "Turkey", "displayname" => "Turkey", "description" => "Turkey", "numsort" => 2170, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TM", "name" => "Turkmenistan", "displayname" => "Turkmenistan", "description" => "Turkmenistan", "numsort" => 2180, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TC", "name" => "Turks and Caicos Islands", "displayname" => "Turks and Caicos Islands", "description" => "Turks and Caicos Islands", "numsort" => 2190, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "TV", "name" => "Tuvalu", "displayname" => "Tuvalu", "description" => "Tuvalu", "numsort" => 2200, "status" => 1, ]); 
        DB::table("nationality")->insert([ "code" => "UG", "name" => "Uganda ", "displayname" => "Uganda ", "description" => "Uganda ", "numsort" => 2210, "status" => 1, ]); 
        
    }
}
